import { MainboardLayout, MainboardZone, MainboardLayoutItemType } from '../common';

export const MAINBOARD_CONFIG_FIELDS = {
  [MainboardLayout.FULLSCREEN]: {
    prefix: MainboardLayout.FULLSCREEN,
    defaultZone: MainboardZone.FULLSCREEN_ZONE5,
    container: {
      left: 0,
      top: 0,
      width: 100,
      height: 100,
    },
    accentLines: [
      {
        left: 16.7,
        top: 0,
        width: 0.2,
        height: 100,
      },
    ],
    [MainboardZone.FULLSCREEN_ZONE5]: {
      prefix: MainboardZone.FULLSCREEN_ZONE5,
      items: [
        {
          prefix: 'item-0',
          left: 0,
          top: 0,
          width: 16.7,
          height: 100,
          types: [MainboardLayoutItemType.IMAGE_VIDEO],
          defaultType: MainboardLayoutItemType.IMAGE_VIDEO,
        },
        {
          prefix: 'item-1',
          left: 16.7,
          top: 0,
          width: 41.65,
          height: 50,
          types: [MainboardLayoutItemType.IMAGE],
          defaultType: MainboardLayoutItemType.IMAGE,
        },
        {
          prefix: 'item-2',
          left: 16.7,
          top: 50,
          width: 41.65,
          height: 50,
          types: [MainboardLayoutItemType.CARD_CONTENT, MainboardLayoutItemType.ANALYTICS],
          defaultType: MainboardLayoutItemType.ANALYTICS,
        },
        {
          prefix: 'item-3',
          left: 58.35,
          top: 0,
          width: 41.65,
          height: 50,
          types: [MainboardLayoutItemType.CARD_CONTENT, MainboardLayoutItemType.IMAGE],
          defaultType: MainboardLayoutItemType.CARD_CONTENT,
        },
        {
          prefix: 'item-4',
          left: 58.35,
          top: 50,
          width: 41.65,
          height: 50,
          types: [MainboardLayoutItemType.CARD_RESPONSE, MainboardLayoutItemType.CARD_RESPONSE_TREND],
          defaultType: MainboardLayoutItemType.CARD_RESPONSE,
        },
      ],
    },
    [MainboardZone.FULLSCREEN_ZONE4]: {
      prefix: MainboardZone.FULLSCREEN_ZONE4,
      items: [
        {
          prefix: 'item-0',
          left: 0,
          top: 0,
          width: 16.7,
          height: 100,
          types: [MainboardLayoutItemType.IMAGE_VIDEO],
          defaultType: MainboardLayoutItemType.IMAGE_VIDEO,
        },
        {
          prefix: 'item-1',
          left: 16.7,
          top: 0,
          width: 83.3,
          height: 50,
          types: [MainboardLayoutItemType.CARD_CONTENT, MainboardLayoutItemType.IMAGE],
          defaultType: MainboardLayoutItemType.CARD_CONTENT,
        },
        {
          prefix: 'item-2',
          left: 16.7,
          top: 50,
          width: 41.65,
          height: 50,
          types: [MainboardLayoutItemType.CARD_CONTENT, MainboardLayoutItemType.ANALYTICS],
          defaultType: MainboardLayoutItemType.ANALYTICS,
        },
        {
          prefix: 'item-3',
          left: 58.35,
          top: 50,
          width: 41.65,
          height: 50,
          types: [MainboardLayoutItemType.CARD_RESPONSE, MainboardLayoutItemType.CARD_RESPONSE_TREND],
          defaultType: MainboardLayoutItemType.CARD_RESPONSE,
        },
      ],
    },
    [MainboardZone.LEADERBOARD]: {
      prefix: MainboardZone.LEADERBOARD,
      items: [
        {
          prefix: 'item-0',
          left: 0,
          top: 0,
          width: 16.7,
          height: 100,
          types: [MainboardLayoutItemType.LIVE_RESPONSE, MainboardLayoutItemType.IMAGE_VIDEO],
          defaultType: MainboardLayoutItemType.LIVE_RESPONSE,
        },
        {
          prefix: 'item-1',
          left: 16.7,
          top: 0,
          width: 83.3,
          height: 50,
          types: [MainboardLayoutItemType.IMAGE],
          defaultType: MainboardLayoutItemType.IMAGE,
        },
        {
          prefix: 'item-2',
          left: 16.7,
          top: 50,
          width: 83.3,
          height: 50,
          types: [MainboardLayoutItemType.LEADERBOARD],
          defaultType: MainboardLayoutItemType.LEADERBOARD,
        },
      ],
    },
  },
  [MainboardLayout.SIDESLAB]: {
    prefix: MainboardLayout.SIDESLAB,
    defaultZone: MainboardZone.SIDESLAB_ZONE3,
    container: {
      left: 66.67,
      top: 0,
      width: 33.33,
      height: 100,
    },
    accentLines: [
      {
        left: 66.67,
        top: 0,
        width: 0.2,
        height: 100,
      },
    ],
    [MainboardZone.SIDESLAB_ZONE3]: {
      prefix: MainboardZone.SIDESLAB_ZONE3,
      items: [
        {
          prefix: 'item-0',
          left: 66.67,
          top: 0,
          width: 33.33,
          height: 33.33,
          types: [MainboardLayoutItemType.ANALYTICS, MainboardLayoutItemType.IMAGE],
          defaultType: MainboardLayoutItemType.ANALYTICS,
        },
        {
          prefix: 'item-1',
          left: 66.67,
          top: 33.33,
          width: 33.33,
          height: 33.33,
          types: [MainboardLayoutItemType.CARD_CONTENT, MainboardLayoutItemType.IMAGE],
          defaultType: MainboardLayoutItemType.CARD_CONTENT,
        },
        {
          prefix: 'item-2',
          left: 66.67,
          top: 66.67,
          width: 33.33,
          height: 33.34,
          types: [MainboardLayoutItemType.CARD_RESPONSE, MainboardLayoutItemType.CARD_RESPONSE_TREND],
          defaultType: MainboardLayoutItemType.CARD_RESPONSE,
        },
      ],
    },
    [MainboardZone.SIDESLAB_ZONE2]: {
      prefix: MainboardZone.SIDESLAB_ZONE2,
      items: [
        {
          prefix: 'item-0',
          left: 66.67,
          top: 0,
          width: 33.33,
          height: 50,
          types: [MainboardLayoutItemType.CARD_CONTENT, MainboardLayoutItemType.IMAGE],
          defaultType: MainboardLayoutItemType.CARD_CONTENT,
        },
        {
          prefix: 'item-1',
          left: 66.67,
          top: 50,
          width: 33.33,
          height: 50,
          types: [MainboardLayoutItemType.CARD_RESPONSE, MainboardLayoutItemType.CARD_RESPONSE_TREND],
          defaultType: MainboardLayoutItemType.CARD_RESPONSE,
        },
      ],
    },
    [MainboardZone.LEADERBOARD]: {
      prefix: MainboardZone.LEADERBOARD,
      items: [
        {
          prefix: 'item-0',
          left: 0,
          top: 0,
          width: 16.7,
          height: 100,
          types: [MainboardLayoutItemType.LIVE_RESPONSE],
          defaultType: MainboardLayoutItemType.LIVE_RESPONSE,
        },
        {
          prefix: 'item-1',
          left: 66.67,
          top: 0,
          width: 33.33,
          height: 33.33,
          types: [MainboardLayoutItemType.IMAGE],
          defaultType: MainboardLayoutItemType.IMAGE,
        },
        {
          prefix: 'item-2',
          left: 66.67,
          top: 33.33,
          width: 33.33,
          height: 66.67,
          types: [MainboardLayoutItemType.LEADERBOARD],
          defaultType: MainboardLayoutItemType.LEADERBOARD,
        },
      ],
    },
  },
  [MainboardLayout.LOWER_THIRD]: {
    prefix: MainboardLayout.LOWER_THIRD,
    defaultZone: MainboardZone.LOWER_THIRD_ZONE3,
    container: {
      left: 0,
      top: 75,
      width: 100,
      height: 25,
    },
    accentLines: [
      {
        left: 0,
        top: 75,
        width: 100,
        height: 0.2,
      },
    ],
    [MainboardZone.LOWER_THIRD_ZONE3]: {
      prefix: MainboardZone.LOWER_THIRD_ZONE3,
      items: [
        {
          prefix: 'item-0',
          left: 0,
          top: 75,
          width: 33.33,
          height: 25,
          types: [MainboardLayoutItemType.ANALYTICS, MainboardLayoutItemType.IMAGE],
          defaultType: MainboardLayoutItemType.ANALYTICS,
        },
        {
          prefix: 'item-1',
          left: 33.33,
          top: 75,
          width: 33.33,
          height: 25,
          types: [MainboardLayoutItemType.CARD_CONTENT, MainboardLayoutItemType.IMAGE],
          defaultType: MainboardLayoutItemType.CARD_CONTENT,
        },
        {
          prefix: 'item-2',
          left: 66.67,
          top: 75,
          width: 33.33,
          height: 25,
          types: [MainboardLayoutItemType.CARD_RESPONSE, MainboardLayoutItemType.CARD_RESPONSE_TREND],
          defaultType: MainboardLayoutItemType.CARD_RESPONSE,
        },
      ],
    },
    [MainboardZone.LOWER_THIRD_ZONE2]: {
      prefix: MainboardZone.LOWER_THIRD_ZONE2,
      items: [
        {
          prefix: 'item-0',
          left: 0,
          top: 75,
          width: 50,
          height: 25,
          types: [MainboardLayoutItemType.CARD_CONTENT, MainboardLayoutItemType.IMAGE],
          defaultType: MainboardLayoutItemType.CARD_CONTENT,
        },
        {
          prefix: 'item-1',
          left: 50,
          top: 75,
          width: 50,
          height: 25,
          types: [MainboardLayoutItemType.CARD_RESPONSE, MainboardLayoutItemType.CARD_RESPONSE_TREND],
          defaultType: MainboardLayoutItemType.CARD_RESPONSE,
        },
      ],
    },
    [MainboardZone.LEADERBOARD]: {
      prefix: MainboardZone.LEADERBOARD,
      items: [
        {
          prefix: 'item-0',
          left: 0,
          top: 0,
          width: 16.7,
          height: 75,
          types: [MainboardLayoutItemType.LIVE_RESPONSE],
          defaultType: MainboardLayoutItemType.LIVE_RESPONSE,
        },
        {
          prefix: 'item-1',
          left: 0,
          top: 75,
          width: 50,
          height: 25,
          types: [MainboardLayoutItemType.IMAGE],
          defaultType: MainboardLayoutItemType.IMAGE,
        },
        {
          prefix: 'item-2',
          left: 50,
          top: 75,
          width: 50,
          height: 25,
          types: [MainboardLayoutItemType.LEADERBOARD],
          defaultType: MainboardLayoutItemType.LEADERBOARD,
        },
      ],
    },
  },
};
